export const keys = {
  PRELOAD_TIMEOUT: 2500,
  STAKE_FEE: 0,
  STAKE_APY: 500,
  STAKE_DURATION: "30D",
  STAKE_DURATION_VALUE: 300,
  STAKE_DURATION_TEXT: "thirty days",
  STAKE_OPTION_ID: 0,
};
